/**INTERNALS*/
import { CharacterDomain } from '../entity/character.entity';

/**CHARACTERS*/
import { EquipmentSlot } from '@characters/util/model';

export const MOCK_CHARACTERS: CharacterDomain[] = [
  {
    id: '1',
    name: 'Aldrin',
    level: '15',
    faction: 'Alliance',
    race: 'Orc',
    class: 'Warrior',
    profession: 'Blacksmithing',
    health: '150',
    mana: '30',
    strength: '20',
    agility: '10',
    intellect: '5',
    stamina: '15',
    armor: '25',
    abilities: [
      { name: 'Cleave', description: 'Deals damage to all enemies in front.', cooldown: '10' },
      { name: 'Battle Shout', description: 'Increases allies\' attack power.', cooldown: '15' },
    ],
    biography: 'Aldrin is a fearless Orc Warrior known for his strength and bravery on the battlefield.',
    equipment: [
      { name: 'Iron Sword', slot: EquipmentSlot.Weapon as string, rarity: 'Rare', stats: [{ statType: 'Damage', value: '10' }] },
      { name: 'Iron Shield', slot: EquipmentSlot.Shield as string, rarity: 'Common', stats: [{ statType: 'Armor', value: '15' }] },
    ],
  },
  {
    id: '2',
    name: 'Lirael',
    level: '7',
    faction: 'Alliance',
    race: 'Gnome',
    class: 'Rogue',
    profession: 'Engineering',
    health: '120',
    mana: '50',
    strength: '10',
    agility: '25',
    intellect: '10',
    stamina: '10',
    armor: '15',
    abilities: [
      { name: 'Backstab', description: 'Deals damage to the target and stuns them.', cooldown: '20' },
      { name: 'Evasion', description: 'Increases dodge chance for a short duration.', cooldown: '30' },
    ],
    biography: 'Lirael is a masterful Gnome Rogue known for her agility and cunning tactics.',
    equipment: [
      { name: 'Dagger of Shadows', slot: EquipmentSlot.Weapon as string, rarity: 'Epic', stats: [{ statType: 'Damage', value: '8' }] },
      { name: 'Cloak of Stealth', slot: EquipmentSlot.Chest as string, rarity: 'Uncommon', stats: [{ statType: 'Agility', value: '5' }] },
    ],
  },
  {
    id: '3',
    name: 'Thrain',
    level: '8',
    faction: 'Horde',
    race: 'Tauren',
    class: 'Druid',
    profession: 'Alchemy',
    health: '160',
    mana: '60',
    strength: '15',
    agility: '10',
    intellect: '20',
    stamina: '15',
    armor: '30',
    abilities: [
      { name: 'Entangling Roots', description: 'Roots the target in place.', cooldown: '15' },
      { name: 'Healing Touch', description: 'Heals a friendly target.', cooldown: '10' },
    ],
    biography: 'Thrain is a wise Tauren Druid known for his healing abilities and deep connection with nature.',
    equipment: [
      { name: 'Staff of the Forest', slot: EquipmentSlot.Weapon as string, rarity: 'Rare', stats: [{ statType: 'Intellect', value: '10' }] },
      { name: 'Druidic Robes', slot: EquipmentSlot.Chest as string, rarity: 'Uncommon', stats: [{ statType: 'Health', value: '20' }] },
    ],
  },
  {
    id: '4',
    name: 'Riven',
    level: '10',
    faction: 'Alliance',
    race: 'Human',
    class: 'Paladin',
    profession: 'Jewelcrafting',
    health: '180',
    mana: '40',
    strength: '22',
    agility: '12',
    intellect: '15',
    stamina: '20',
    armor: '35',
    abilities: [
      { name: 'Holy Strike', description: 'Deals holy damage to an enemy.', cooldown: '12' },
      { name: 'Divine Shield', description: 'Makes you immune to damage for a short time.', cooldown: '60' },
    ],
    biography: 'Riven is a noble Human Paladin who fights for justice and protects the weak.',
    equipment: [
      { name: 'Holy Avenger', slot: EquipmentSlot.Weapon as string, rarity: 'Legendary', stats: [{ statType: 'Damage', value: '15' }] },
      { name: 'Plate Armor', slot: EquipmentSlot.Chest as string, rarity: 'Epic', stats: [{ statType: 'Armor', value: '25' }] },
    ],
  },
  {
    id: '5',
    name: 'Elowen',
    level: '9',
    faction: 'Alliance',
    race: 'Draenei',
    class: 'Mage',
    profession: 'Enchanting',
    health: '110',
    mana: '100',
    strength: '5',
    agility: '10',
    intellect: '30',
    stamina: '10',
    armor: '10',
    abilities: [
      { name: 'Frostbolt', description: 'Deals frost damage to a target and slows them.', cooldown: '8' },
      { name: 'Arcane Missiles', description: 'Launches a series of arcane missiles at the enemy.', cooldown: '15' },
    ],
    biography: 'Elowen is an enigmatic Draenei Mage who wields powerful arcane magic.',
    equipment: [
      { name: 'Staff of Arcane Power', slot: EquipmentSlot.Weapon as string, rarity: 'Epic', stats: [{ statType: 'Intellect', value: '12' }] },
      { name: 'Robe of the Arcane', slot: EquipmentSlot.Chest as string, rarity: 'Rare', stats: [{ statType: 'Mana', value: '30' }] },
    ],
  },
  {
    id: '6',
    name: 'Gromak',
    level: '6',
    faction: 'Horde',
    race: 'Undead',
    class: 'Warlock',
    profession: 'Herbalism',
    health: '140',
    mana: '70',
    strength: '10',
    agility: '5',
    intellect: '25',
    stamina: '15',
    armor: '20',
    abilities: [
      { name: 'Shadow Bolt', description: 'Deals shadow damage to an enemy.', cooldown: '10' },
      { name: 'Summon Imp', description: 'Summons a minor demon to aid in battle.', cooldown: '30' },
    ],
    biography: 'Gromak is an Undead Warlock who harnesses the powers of dark magic.',
    equipment: [
      { name: 'Staff of Dark Magic', slot: EquipmentSlot.Weapon as string, rarity: 'Rare', stats: [{ statType: 'Intellect', value: '10' }] },
      { name: 'Robe of Shadows', slot: EquipmentSlot.Chest as string, rarity: 'Uncommon', stats: [{ statType: 'Armor', value: '15' }] },
    ],
  },
  {
    id: '7',
    name: 'Thalia',
    level: '11',
    faction: 'Alliance',
    race: 'Human',
    class: 'Priest',
    profession: 'Alchemy',
    health: '130',
    mana: '90',
    strength: '8',
    agility: '6',
    intellect: '28',
    stamina: '14',
    armor: '18',
    abilities: [
      { name: 'Heal', description: 'Heals a friendly target.', cooldown: '8' },
      { name: 'Holy Fire', description: 'Deals damage and heals the caster.', cooldown: '12' },
    ],
    biography: 'Thalia is a compassionate Human Priest dedicated to healing her allies.',
    equipment: [
      { name: 'Staff of the Light', slot: EquipmentSlot.Weapon as string, rarity: 'Epic', stats: [{ statType: 'Intellect', value: '10' }] },
      { name: 'Lightforged Robe', slot: EquipmentSlot.Chest as string, rarity: 'Rare', stats: [{ statType: 'Health', value: '20' }] },
    ],
  },
  {
    id: '8',
    name: 'Zara',
    level: '12',
    faction: 'Horde',
    race: 'Goblin',
    class: 'Warrior',
    profession: 'Engineering',
    health: '125',
    mana: '50',
    strength: '15',
    agility: '30',
    intellect: '12',
    stamina: '10',
    armor: '16',
    abilities: [
      { name: 'Demon Leap', description: 'Leaps to a target location, dealing damage.', cooldown: '20' },
      { name: 'Metamorphosis', description: 'Transforms into a demon for increased power.', cooldown: '60' },
    ],
    biography: 'Zara is a fierce Goblin Warrior known for her agility and quick reflexes.',
    equipment: [
      { name: 'Twin Blades of Destruction', slot: EquipmentSlot.Weapon as string, rarity: 'Legendary', stats: [{ statType: 'Damage', value: '20' }] },
      { name: 'Goblin Battle Armor', slot: EquipmentSlot.Chest as string, rarity: 'Epic', stats: [{ statType: 'Armor', value: '25' }] },
    ],
  },
  {
    id: '9',
    name: 'Kael',
    level: '5',
    faction: 'Alliance',
    race: 'Night Elf',
    class: 'Hunter',
    profession: 'Leatherworking',
    health: '110',
    mana: '40',
    strength: '12',
    agility: '22',
    intellect: '8',
    stamina: '10',
    armor: '12',
    abilities: [
      { name: 'Arcane Shot', description: 'Deals arcane damage to the target.', cooldown: '8' },
      { name: 'Multi-Shot', description: 'Fires multiple arrows at nearby enemies.', cooldown: '12' },
    ],
    biography: 'Kael is a skilled Night Elf Hunter who excels at long-range combat.',
    equipment: [
      { name: 'Longbow of Precision', slot: EquipmentSlot.Weapon as string, rarity: 'Epic', stats: [{ statType: 'Agility', value: '12' }] },
      { name: 'Hunter\'s Vest', slot: EquipmentSlot.Chest as string, rarity: 'Rare', stats: [{ statType: 'Stamina', value: '8' }] },
    ],
  },
  {
    id: '10',
    name: 'Morgana',
    level: '9',
    faction: 'Horde',
    race: 'Troll',
    class: 'Shaman',
    profession: 'Jewelcrafting',
    health: '130',
    mana: '80',
    strength: '10',
    agility: '8',
    intellect: '25',
    stamina: '12',
    armor: '18',
    abilities: [
      { name: 'Chain Lightning', description: 'Strikes multiple enemies with lightning.', cooldown: '15' },
      { name: 'Healing Stream', description: 'Summons a totem that heals nearby allies.', cooldown: '20' },
    ],
    biography: 'Morgana is a powerful Troll Shaman who channels the elemental forces to aid her allies.',
    equipment: [
      { name: 'Totem of the Storm', slot: EquipmentSlot.Weapon as string, rarity: 'Epic', stats: [{ statType: 'Intellect', value: '14' }] },
      { name: 'Stormcaller Armor', slot: EquipmentSlot.Chest as string, rarity: 'Rare', stats: [{ statType: 'Armor', value: '18' }] },
    ],
  },
  {
    id: '11',
    name: 'Darius',
    level: '14',
    faction: 'Alliance',
    race: 'Dwarf',
    class: 'Paladin',
    profession: 'Mining',
    health: '175',
    mana: '35',
    strength: '25',
    agility: '10',
    intellect: '12',
    stamina: '22',
    armor: '40',
    abilities: [
      { name: 'Judgment', description: 'Judges the target, dealing holy damage.', cooldown: '10' },
      { name: 'Hammer of Justice', description: 'Stuns the target.', cooldown: '20' },
    ],
    biography: 'Darius is a stoic Dwarf Paladin who stands as a bulwark against evil.',
    equipment: [
      { name: 'Hammer of the Righteous', slot: EquipmentSlot.Weapon as string, rarity: 'Legendary', stats: [{ statType: 'Damage', value: '20' }] },
      { name: 'Paladin Plate', slot: EquipmentSlot.Chest as string, rarity: 'Epic', stats: [{ statType: 'Armor', value: '30' }] },
    ],
  },
  {
    id: '12',
    name: 'Naria',
    level: '13',
    faction: 'Horde',
    race: 'Blood Elf',
    class: 'Hunter',
    profession: 'Skinning',
    health: '120',
    mana: '50',
    strength: '15',
    agility: '30',
    intellect: '10',
    stamina: '12',
    armor: '16',
    abilities: [
      { name: 'Serpent Sting', description: 'Deals nature damage over time.', cooldown: '10' },
      { name: 'Rapid Fire', description: 'Increases attack speed for a short time.', cooldown: '20' },
    ],
    biography: 'Naria is a swift and agile Blood Elf Hunter, known for her deadly precision.',
    equipment: [
      { name: 'Bow of the Phoenix', slot: EquipmentSlot.Weapon as string, rarity: 'Legendary', stats: [{ statType: 'Agility', value: '18' }] },
      { name: 'Phoenix Armor', slot: EquipmentSlot.Chest as string, rarity: 'Epic', stats: [{ statType: 'Armor', value: '22' }] },
    ],
  },
];

