import { CharacterDomain } from '../entity/character.entity';

export const MOCK_CHARACTERS: CharacterDomain[] = [
  {
    id: '1',
    name: 'Aldrin',
    level: '5',
    faction: 'Horde',
    race: 'Orc',
    class: 'Warrior',
    profession: 'Blacksmithing',
    health: '150',
    mana: '30',
    strength: '20',
    agility: '10',
    intellect: '5',
    stamina: '15',
    armor: '25',
    abilities: [
      { name: 'Cleave', description: 'Deals damage to all enemies in front.', cooldown: '10' },
      { name: 'Battle Shout', description: 'Increases allies\' attack power.', cooldown: '15' },
    ],
    biography: 'Aldrin is a fearless Orc Warrior known for his strength and bravery on the battlefield.',
    equipment: [
      { name: 'Iron Sword', slot: 'Main Hand', rarity: 'Rare', stats: [{ statType: 'Damage', value: '10' }] },
      { name: 'Iron Shield', slot: 'Off Hand', rarity: 'Common', stats: [{ statType: 'Armor', value: '15' }] },
    ],
  },
  {
    id: '2',
    name: 'Lirael',
    level: '7',
    faction: 'Alliance',
    race: 'Gnome',
    class: 'Rogue',
    profession: 'Engineering',
    health: '120',
    mana: '50',
    strength: '10',
    agility: '25',
    intellect: '10',
    stamina: '10',
    armor: '15',
    abilities: [
      { name: 'Backstab', description: 'Deals damage to the target and stuns them.', cooldown: '20' },
      { name: 'Evasion', description: 'Increases dodge chance for a short duration.', cooldown: '30' },
    ],
    biography: 'Lirael is a masterful Gnome sRogue known for her agility and cunning tactics.',
    equipment: [
      { name: 'Dagger of Shadows', slot: 'Main Hand', rarity: 'Epic', stats: [{ statType: 'Damage', value: '8' }] },
      { name: 'Cloak of Stealth', slot: 'Back', rarity: 'Uncommon', stats: [{ statType: 'Agility', value: '5' }] },
    ],
  },
  {
    id: '3',
    name: 'Thrain',
    level: '8',
    faction: 'Horde',
    race: 'Tauren',
    class: 'Druid',
    profession: 'Alchemy',
    health: '160',
    mana: '60',
    strength: '15',
    agility: '10',
    intellect: '20',
    stamina: '15',
    armor: '30',
    abilities: [
      { name: 'Entangling Roots', description: 'Roots the target in place.', cooldown: '15' },
      { name: 'Healing Touch', description: 'Heals a friendly target.', cooldown: '10' },
    ],
    biography: 'Thrain is a wise Tauren Druid known for his healing abilities and deep connection with nature.',
    equipment: [
      { name: 'Staff of the Forest', slot: 'Main Hand', rarity: 'Rare', stats: [{ statType: 'Intellect', value: '10' }] },
      { name: 'Druidic Robes', slot: 'Chest', rarity: 'Uncommon', stats: [{ statType: 'Health', value: '20' }] },
    ],
  },
  {
    id: '4',
    name: 'Riven',
    level: '10',
    faction: 'Alliance',
    race: 'Human',
    class: 'Paladin',
    profession: 'Jewelcrafting',
    health: '180',
    mana: '40',
    strength: '22',
    agility: '12',
    intellect: '15',
    stamina: '20',
    armor: '35',
    abilities: [
      { name: 'Holy Strike', description: 'Deals holy damage to an enemy.', cooldown: '12' },
      { name: 'Divine Shield', description: 'Makes you immune to damage for a short time.', cooldown: '60' },
    ],
    biography: 'Riven is a noble Human Paladin who fights for justice and protects the weak.',
    equipment: [
      { name: 'Holy Avenger', slot: 'Main Hand', rarity: 'Legendary', stats: [{ statType: 'Damage', value: '15' }] },
      { name: 'Plate Armor', slot: 'Chest', rarity: 'Epic', stats: [{ statType: 'Armor', value: '25' }] },
    ],
  },
  {
    id: '5',
    name: 'Elowen',
    level: '9',
    faction: 'Alliance',
    race: 'Draenei',
    class: 'Mage',
    profession: 'Enchanting',
    health: '110',
    mana: '100',
    strength: '5',
    agility: '10',
    intellect: '30',
    stamina: '10',
    armor: '10',
    abilities: [
      { name: 'Frostbolt', description: 'Deals frost damage to a target and slows them.', cooldown: '8' },
      { name: 'Arcane Missiles', description: 'Launches a series of arcane missiles at the enemy.', cooldown: '15' },
    ],
    biography: 'Elowen is an enigmatic Draenei Mage who wields powerful arcane magic.',
    equipment: [
      { name: 'Staff of Arcane Power', slot: 'Main Hand', rarity: 'Epic', stats: [{ statType: 'Intellect', value: '12' }] },
      { name: 'Robe of the Arcane', slot: 'Chest', rarity: 'Rare', stats: [{ statType: 'Mana', value: '30' }] },
    ],
  },
  {
    id: '6',
    name: 'Gromak',
    level: '6',
    faction: 'Horde',
    race: 'Undead',
    class: 'Warlock',
    profession: 'Herbalism',
    health: '140',
    mana: '70',
    strength: '10',
    agility: '5',
    intellect: '25',
    stamina: '15',
    armor: '20',
    abilities: [
      { name: 'Shadow Bolt', description: 'Deals shadow damage to an enemy.', cooldown: '10' },
      { name: 'Summon Imp', description: 'Summons a minor demon to aid in battle.', cooldown: '30' },
    ],
    biography: 'Gromak is an Undead Warlock who harnesses the powers of dark magic.',
    equipment: [
      { name: 'Staff of Dark Magic', slot: 'Main Hand', rarity: 'Rare', stats: [{ statType: 'Intellect', value: '10' }] },
      { name: 'Robe of Shadows', slot: 'Chest', rarity: 'Uncommon', stats: [{ statType: 'Armor', value: '15' }] },
    ],
  },
  {
    id: '7',
    name: 'Thalia',
    level: '11',
    faction: 'Alliance',
    race: 'Human',
    class: 'Priest',
    profession: 'Alchemy',
    health: '130',
    mana: '90',
    strength: '8',
    agility: '6',
    intellect: '28',
    stamina: '14',
    armor: '18',
    abilities: [
      { name: 'Heal', description: 'Heals a friendly target.', cooldown: '8' },
      { name: 'Holy Fire', description: 'Deals damage and heals the caster.', cooldown: '12' },
    ],
    biography: 'Thalia is a compassionate Human Priest dedicated to healing her allies.',
    equipment: [
      { name: 'Staff of the Light', slot: 'Main Hand', rarity: 'Epic', stats: [{ statType: 'Intellect', value: '10' }] },
      { name: 'Lightforged Robe', slot: 'Chest', rarity: 'Rare', stats: [{ statType: 'Health', value: '20' }] },
    ],
  },
  {
    id: '8',
    name: 'Zara',
    level: '12',
    faction: 'Horde',
    race: 'Goblin',
    class: 'Warrior',
    profession: 'Engineering',
    health: '125',
    mana: '50',
    strength: '15',
    agility: '30',
    intellect: '12',
    stamina: '10',
    armor: '16',
    abilities: [
      { name: 'Demon Leap', description: 'Leaps to a target location, dealing damage.', cooldown: '20' },
      { name: 'Metamorphosis', description: 'Transforms into a demon for increased power.', cooldown: '60' },
    ],
    biography: 'Zara is a fierce Goblin Warrior known for her agility and quick reflexes.',
    equipment: [
      { name: 'Twin Blades', slot: 'Main Hand', rarity: 'Epic', stats: [{ statType: 'Damage', value: '18' }] },
      { name: 'Demon Hunter Armor', slot: 'Chest', rarity: 'Rare', stats: [{ statType: 'Agility', value: '12' }] },
    ],
  },
  {
    id: '9',
    name: 'Kaelith',
    level: '10',
    faction: 'Alliance',
    race: 'Dwarf',
    class: 'Hunter',
    profession: 'Mining',
    health: '140',
    mana: '60',
    strength: '12',
    agility: '20',
    intellect: '8',
    stamina: '16',
    armor: '22',
    abilities: [
      { name: 'Arcane Shot', description: 'Fires an arcane arrow at the enemy.', cooldown: '10' },
      { name: 'Feign Death', description: 'Pretends to be dead, avoiding damage.', cooldown: '20' },
    ],
    biography: 'Kaelith is a skilled Dwarf Hunter, famed for his tracking and archery skills.',
    equipment: [
      { name: 'Longbow of the Elves', slot: 'Main Hand', rarity: 'Epic', stats: [{ statType: 'Damage', value: '12' }] },
      { name: 'Camouflage Cloak', slot: 'Back', rarity: 'Rare', stats: [{ statType: 'Agility', value: '8' }] },
    ],
  },
  {
    id: '10',
    name: 'Rashaad',
    level: '6',
    faction: 'Horde',
    race: 'Troll',
    class: 'Shaman',
    profession: 'Herbalism',
    health: '155',
    mana: '70',
    strength: '14',
    agility: '10',
    intellect: '20',
    stamina: '12',
    armor: '28',
    abilities: [
      { name: 'Lightning Bolt', description: 'Launches a bolt of lightning at the enemy.', cooldown: '8' },
      { name: 'Healing Wave', description: 'Heals a target over time.', cooldown: '15' },
    ],
    biography: 'Rashaad is a cunning Troll Shaman who commands the powers of nature.',
    equipment: [
      { name: 'Totem of the Elements', slot: 'Main Hand', rarity: 'Uncommon', stats: [{ statType: 'Intellect', value: '7' }] },
      { name: 'Shaman Armor', slot: 'Chest', rarity: 'Rare', stats: [{ statType: 'Health', value: '25' }] },
    ],
  },
  {
    id: '11',
    name: 'Xandria',
    level: '9',
    faction: 'Alliance',
    race: 'Gnome',
    class: 'Mage',
    profession: 'Engineering',
    health: '110',
    mana: '100',
    strength: '5',
    agility: '8',
    intellect: '30',
    stamina: '9',
    armor: '10',
    abilities: [
      { name: 'Fireball', description: 'Launches a fiery projectile at the enemy.', cooldown: '10' },
      { name: 'Teleport', description: 'Teleports to a nearby location.', cooldown: '30' },
    ],
    biography: 'Xandria is a brilliant Gnome Mage known for her inventions and spellcasting.',
    equipment: [
      { name: 'Wand of Fire', slot: 'Main Hand', rarity: 'Rare', stats: [{ statType: 'Intellect', value: '12' }] },
      { name: 'Robe of the Arcane', slot: 'Chest', rarity: 'Uncommon', stats: [{ statType: 'Armor', value: '8' }] },
    ],
  },
  {
    id: '12',
    name: 'Brom',
    level: '5',
    faction: 'Horde',
    race: 'Tauren',
    class: 'Warrior',
    profession: 'Mining',
    health: '160',
    mana: '50',
    strength: '25',
    agility: '8',
    intellect: '7',
    stamina: '18',
    armor: '30',
    abilities: [
      { name: 'Death Strike', description: 'Deals damage and heals for a percentage of damage done.', cooldown: '12' },
      { name: 'Raise Dead', description: 'Raises a fallen enemy as an undead minion.', cooldown: '60' },
    ],
    biography: 'Brom is a formidable Tauren Warrior, feared for his dark powers and combat skills.',
    equipment: [
      { name: 'Runeblade of the Undead', slot: 'Main Hand', rarity: 'Legendary', stats: [{ statType: 'Damage', value: '20' }] },
      { name: 'Death Knight Armor', slot: 'Chest', rarity: 'Rare', stats: [{ statType: 'Armor', value: '35' }] },
    ],
  },
];
